services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0

  orleans-host:
    build:
      context: ./AzureContainerApps.Exercise401.Orleans.Host
      dockerfile: Dockerfile
    image: azure-container-apps-exercise-401-orleans-host:latest
    ports:
      - "8080:8080"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KgMeOQ==;TableEndpoint=http://azurite:10002/devstoreaccount1;
    depends_on:
      - azurite

  api:
    build:
      context: .
      dockerfile: AzureContainerApps.Exercise401.Api/Dockerfile
    image: azure-container-apps-exercise-401-api:latest
    ports:
      - "8081:8080"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KgMeOQ==;TableEndpoint=http://azurite:10002/devstoreaccount1;
    depends_on:
      - orleans-host

  worker:
    build:
      context: ./AzureContainerApps.Exercise401.Worker
      dockerfile: Dockerfile
    image: azure-container-apps-exercise-401-worker:latest
    environment:
      - API_BASE_URL=http://api:8080
    depends_on:
      - api

  orleans-scaler:
    build:
      context: ./AzureContainerApps.Exercise401.Orleans.Scaler
      dockerfile: Dockerfile
    image: azure-container-apps-exercise-401-orleans-scaler:latest
    ports:
      - "8082:8080"
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KgMeOQ==;TableEndpoint=http://azurite:10002/devstoreaccount1;
    depends_on:
      - orleans-host
